### ISSUE TITLE
Support for DisplayAttribute

### ISSUE THREAD

**Issue by ChristopherBrownie** [EPPlusSoftware/EPPlus#1042]
Docs reference supporting `DisplayNameAttribute` and `DescriptionAttribute`.

> ![screenshot of documentation](https://github.com/EPPlusSoftware/EPPlus/assets/48576536/729c32ec-9c5d-48cc-82b3-eeae3141fe32)

Internally we use the `DisplayAttribute` which has similar functionality.
```CSharp
[Display(Name = "", Description = "")]
public string Name { get; set; }
```

Is there a difference? Could EPPlus support this attribute as well?

**Comment by swmal** [comment]
@ChristopherBrownie I have referenced this issue from #1058 which is an issue that summarizes many different feature request on LoadFromCollection.

**Comment by swmal** [comment]
@ChristopherBrownie we have added support for the Display attribute, will be available in the upcoming EPPlus 7.

**Comment by c3hb** [comment]
Awesome, thanks!

**Comment by c3hb** [comment]
Thanks for the support for this feature.

I wanted to highlight a situation I ran into with this. I brought in the new EPPlus version and it ended up throwing an error when trying to run `LoadFromCollection`: "Table Table1 Column Phone Number does not have a unique name.". This is due to having multiple "Phone Number" display values on different properties. Looking into this more the unique column requirement seems to come from excel tables.

The problem for us lies in the potential breaking change of bringing in the new package version. We've thought some ideas below that could help until we are ready to fully implement these display label changes.
- Is it possible to disable custom labels set via `Display`/`DisplayName`/`DisplayDescription` attributes and always use the property name?
- Is it possible to have the underlying value in the excel table header be the property name, while the visible value is the display name?

Thank you for any input.

**Comment by swmal** [comment]
Moved the last comment to a new issue #1311
