### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by yh371174229** [EPPlusSoftware/EPPlus#112]
load a *.xlsx file with big data (about 300000 records)，
1. I create a xlsx file with 4 sheets by copying xlsx template.
2. I use Epplus to  append 300000 records
3. save package
4. I open the xlsx file  again，and i want to appent data to other sheet,but when I create a new ExcelPackage object,I reveived a error about OutOfMemory.
```
FileInfo file = new FileInfo(fileName);
using (var package = new ExcelPackage(file)) //this will get a error System.OutOfMemoryException
{

}
```
I googled information,but it didn't help.
1. I can't change my project to x64
2. I use using to manage package  object and sheet object
3. I adjust the order about export data,first I export little data to excel ,then I export big data to excel ,then I successd.

Is this a bug ?
any help will appreciated！I'm looking forward to hearing from you.

**Comment by JanKallman** [comment]
Hello, 
As the error message says you are out of memory.
Running in a x32 context has limited memory, so if you can't change to x64 you have to limit the size of the document.

**Comment by yh371174229** [comment]
@JanKallman  thank you for your reply,I will try to move the excelHelper.cs to a x64 project。

**Comment by yh371174229** [comment]
@JanKallman  Thanks for your replying. 
Unfortunately I can't change to x64.When I open multiple excel file will also get this error(outOfMemory),Except using `using（var package=new ExcelPackage(fileInfo)）` to collect memory,is there another way to collect memory?

**Comment by joycestick** [comment]
Is this still the case with EPPlus? We used to use EPPlus (v4.n) but wrote our own Excel reading code because of the OutOfMemoryException with large workbooks. I think the issue (as I recall) was that EPPlus effectively unzipped the entire XLSX into memory rather than reading package contents as they were needed.

We are just starting to look at commercial solutions, including EPPlus v5+, but if the OutOfMemoryExceptions are still there for large workbooks then this would be a show stopper.
