### ISSUE TITLE
How do I copy the filter area to a new worksheet?

### ISSUE THREAD

**Issue by Wddy** [EPPlusSoftware/EPPlus#1183]
How do I copy the filter area to a new worksheet？I can do that with Microsoft.Office.Interop。

**Comment by swmal** [comment]
Filters are not included in the [copy function](Copy-Ranges-or-Entire-Worksheets). I'll add this as an enhancement.

They are however included if you copy an entire worksheet via` Workbook.Worksheets.Add(string name, ExcelWorksheet copy) `function.

**Comment by AdrianEPPlus** [comment]
In excel you can have one filter per worksheet and since Excel does not support copying filters we won't either.

But as stated earlier you can copy the whole worksheet and the filters will get copied, but if you only want the filters I would suggest you create a new filter on the new worksheet and copy the relevant data from the original worksheet.
