### ISSUE TITLE
Space should be allowed in module-/worksheet names in VBA

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#1261]
Validation that doesn't allow spaces in VBA module names was recently added in EPPlus. It turns out that it works to have spaces in module names even if Microsoft's documentation states that this is against the naming rules (https://learn.microsoft.com/en-us/office/vba/language/concepts/getting-started/visual-basic-naming-rules). We should therefore allow spaces in the module names to maintain backward compatibility.

**Comment by ses4j** [comment]
I think the issue is with "modules" that are really worksheets.  Of course worksheets can have spaces, and worksheets sort of become module names, or something:

![image](https://github.com/EPPlusSoftware/EPPlus/assets/435529/2dd266ad-2a74-4a07-899c-ad6d38acfc46)

that's an example of the file I was hitting issues with.

**Comment by swmal** [comment]
@ses4j Ok, should be the same validation. Test your workbook with our development nuget package för EPPlus 7 when the build is done ( https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed ) and let me know if it works. There is an icon for build status on the readme in our repo.

**Comment by swmal** [comment]
Released in 7.0.8, should also be fixed in next version of v6
