### ISSUE TITLE
Cell text being picked up with an extra '-' when culture set to fi-FI

### ISSUE THREAD

**Issue by idan-amiel-wk** [EPPlusSoftware/EPPlus#1312]
version used: 7.0.9
project is using .NET7

repo with issue reproduction [here](https://github.com/idan-amiel/EPPlus_Finnish_Issue)

**Comment by OssianEPPlus** [comment]
Hi! This is a bug. 
We've found the cause of this and are working on a fix. We'll let you know once it's available via our [Our NuGet Develop Feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed).

The cause seems to be that "fi-FI" culture uses negative sign `−` instead of `-` . We have some handling for that normally but the custom format in the workbook of `"-#,##0"` slipped past our check for duplicated negative signs.
Thanks for letting us know!
