### ISSUE TITLE
Epplus result differs from excel for number and empty string inequality

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1364]
Excel gives a result of `FALSE` for `=24>""` and a result of `TRUE` for `=24<""`.
EPPlus yields the exact opposite.
Please see attached  workbook. 
I'm sorry I couldn't put together a pull request for this one.
[Empty string inequality.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/14653154/Empty.string.inequality.xlsx)

This is occurring for me in version 6.2.10 and 6.2.18.

**Comment by swmal** [comment]
Hi @colbybhearn,

we have fixed this one and #1365 and it will be released in next version of EPPlus 6. Both of these worked as expected in EPPlus 7, which has a lot of improvements in the formula calculation. You should consider to upgrade from v6 to v7 since we will not provide bug fixes on EPPlus 6 for more than another month or so (until we release v 7.1 - we support the two latest minor versions which currently is 7.0 and 6.2).

**Comment by colbybhearn** [comment]
@swmal Ok, understood. Thanks so much for jumping on these defects (@JanKallman too!). I'll look into v7 again!
