### ISSUE TITLE
Bottleneck in GetNonAlphanumericStartChars

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#140]
We are using EPPlus to do some Excel processing.  One of our processes was running really slowly, so we profiled it in Visual Studio to find the bottleneck.  It turns out ~63% of the cpu time was being spent in IsMatch() within GetNonAlphanumericStartChars().  I was able to modify this function to perform the same logic in less than half the time.  I attached before and after screenshots of the profiling sessions.  I will send a PR with the code change.  If you don't mind, please integrate into your next release.  Thanks!

![before](https://user-images.githubusercontent.com/7612605/85926094-8ff93080-b862-11ea-9fd2-ab3b73a45af9.JPG)
![after](https://user-images.githubusercontent.com/7612605/85926095-92f42100-b862-11ea-8b72-46621f789b9d.JPG)

**Comment by swmal** [comment]
Many thanks @rdhasse  for pointing this out. This is just a simple check if the first or the first two characters of a string are non-alphanumeric. We shouldn't have used Regex at all in the first place (my bad), since this is a function that might be executed many times during a calculation.

The code below, which I just commited to our develop branch (available in our appveyor nuget feed), should hopefully improve it even more. 

```
private string GetNonAlphanumericStartChars(string expr)
{
    var result = string.Empty;
    if (!string.IsNullOrEmpty(expr))
    {
        if (expr.Length > 1 && !char.IsLetterOrDigit(expr[0]) && !char.IsLetterOrDigit(expr[1])) 
            result = expr.Substring(0, 2);
        else if (expr.Length > 0 && !char.IsLetterOrDigit(expr[0])) 
            result = expr.Substring(0, 1);
    }
    return result;
}
```
