### ISSUE TITLE
Approximate VLOOKUP with mixed search value data types

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1755]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.5.2

### Spreadsheet application

Excel

### Description

We encountered an error scenario regarding `VLOOKUP` when used this way:

- `lookup_value` has a custom date format
- values to search in `table_array` have different data types (strings and dates). This appears to me to be the crux of the issue.
- string to search in `table_array` have a second custom date format
- dates to search in `table_array` have a third custom date format 
- values in `col_index_num` are all formatted as percent

Technical argument names from https://support.microsoft.com/en-us/office/vlookup-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1

**Specific example:** 
The first search value is a string like "TODAY" and the rest are formatted date values. Excel returns the correct lookup value, but EPPlus 7.5.x returns #N/A. Experimenting with search values of only a single data type rather than mixed types, VLOOKUP works fine!

PR forthcoming!

**Comment by OssianEPPlus** [comment]
Thank you! We are looking into this.

**Comment by OssianEPPlus** [comment]
Looks like this is due to mixed values and the `range lookup` variable for approximate values. Essentially our binary search can't compute different types at the same time as after comparing a string with a number it can't determine if a string is larger or smaller than e.g an int value. As well. They're not directly comparable.

When the `range_lookup` variable of VLOOKUP is True [Excel (under technical details)](https://support.microsoft.com/en-us/office/vlookup-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1) and Epplus assumes the first column in the range is Either numerically or alphabetically sorted.

If it isn't, Excel itself can return some pretty strange results:
![bild](https://github.com/user-attachments/assets/b3e913ec-48be-4f1c-a11a-bd85aed7ca83)

Having the first column be of mixed string and number datatypes in Excel, makes for similar strange results:
![bild](https://github.com/user-attachments/assets/fa0491b7-0195-4df6-bad5-a9d8930352d5)

Excel does seem to be able to sometimes find values relatively often if both string and numeric values are correctly sorted but fails to do so in e.g. reverse order:
![bild](https://github.com/user-attachments/assets/e8982ce4-5309-4577-9218-ee0b923d1bf3)

Excel's behaviour with mixed values in this case appears to have bugs and inconsistencies which are not covered in the documentation. We're considering what we can do to support mixed values in a future version but do not support mixed values in VLOOKUP currently.

**Comment by colbybhearn** [comment]
@OssianEPPlus Wow, I was clearly not very thorough on this. lol 

I appreciate your diligence, walking through justifying this outcome, and looking into how it might be supported in the future.

We'll try to pivot on how we're performing this lookup in the product for now.
Thanks,
-Colby

**Comment by OssianEPPlus** [comment]
No worries, happy to help. Thanks!
