### ISSUE TITLE
PivotTble withCalculated Field

### ISSUE THREAD

**Issue by SteveWark** [EPPlusSoftware/EPPlus#274]
I've followed your sample code to add a calculated field to a pivottable, the field is calculated correctly but is not getting added into the pivot as the field name is getting a '2' added to it,

`
     // generate caclulated field
     var calcField = pivotTable2.Fields.AddCalculatedField("Total", "'Ordinary'+'TimeHalf'+'DoubleTime'");
     calcField.Format = "#,##0";

    // add field to pivot
     dataField = pivotTable2.DataFields.Add(pivotTable2.Fields["Total"]);
     dataField.Format = "#,##0";
`
However, within the spreadsheet the calculated field is Total2 and if I manually add to the pivot all works as it should

Has anyone encountered this issue, no other fields have the name Total, if I change the pivot field name tot Total2 an error is thrown.

![image](https://user-images.githubusercontent.com/12159493/104409838-37e60980-55bb-11eb-94d9-dac559d1cb2d.png)

**Comment by JanKallman** [comment]
I cant reproduce this. Can you provide me with a reproducible test case?

**Comment by SteveWark** [comment]
Copy of simple test program and spreadsheet produced which duplicates the issue.  It is a Visual Studio 19 .net Console application with EPPlUs package installed via Nuget, plus I added Excel Interop so I could add macro’s to collapse the pivot.

[cid:image001.png@01D6EA4A.03889310]


Cheers
Steve Wark

Steve Wark
[cid:image003.png@01D6EA4A.039F7670]
827 Bridge Creek Road, Binda NSW 2583
Mobile: 0417 253 725

**Comment by JanKallman** [comment]
This happens if you don't set a name on the data field or if you give the data field the same name as the field.
Adding this on the calculated field of the data field resolves the problem...
`dataField.Name = "Sum of Productive";`
This is a little bit weird as this only seems to be happening on calculated fields. I will add a fix giving the data field of the calculated field another default name and check for duplicate names on change, but for now just set another name than 'Productive' on the data field.

**Comment by SteveWark** [comment]
Thanks, just tried this and that fixed it....
