### ISSUE TITLE
SaveAsText doesn't match excel behavior for CSVs

### ISSUE THREAD

**Issue by Mason11987** [EPPlusSoftware/EPPlus#335]
For a pair of cells like so:

`| ABC, 123 | ABC |`

Excel outputs this as the following CSV:

`"ABC, 123", ABC`

When using worksheet.Cells[].SaveAsText() with the default ExcelOuptutTextFormat() those cells are output as:

`ABC, 123, ABC`

With ExcelOuptutTextFormat() { TextQualifier ='\"' } those cells are output as:

`"ABC, 123, "ABC"`

It looks like there is not a way to output exact as excel does, using the text qualifier when needed (included commas, maybe included double quotes?)

**Comment by drcolombo** [comment]
I think the problem is a bit more extensive. After a bit of testing and digging into the code I can make the following conclusions:
1. the delimeter is hard-coded in the code (yes, you can change it via ExcelTextFormatBase, but by default it doesn't depend on the current culture);
2. depending on the region settings Excel uses "List separator" from Windows region settings as the delimeter (so it's not comma even by default!);
3. only if a cell text value contains the delimeter, it will add double quotes like in the @Mason11987 example. In case of let's say German region settings the output will be
`ABC, 123; ABC`
because the delimeter in this case is ';'.
The fact that Excel uses "List separator" from Windows region setting as a delimeter is just my guess after a short testing with different region settings.

**Comment by JanKallman** [comment]
SaveAsText is not written as a replica of the Save As - CSV in Excel. 
EPPlus will use "," as a delimiter by default. If you want it to default to current culture, set it to CultureInfo.CurrentCulture.TextInfo.ListSeparator.
Using the TextQualifier will wrap all string cells in double quotes (not exactly as Excel do, but the file will open correctly).
For example:
`ws.Cells["a1:B1"].SaveToText(new FileInfo("TestFile.csv"), new ExcelOutputTextFormat() { TextQualifier = '"', Delimiter=';' });`
Will result in:
"ABC,123";"ABC"
...to be opened with Swedish regional settings.
