### ISSUE TITLE
Load Collection with Attributes not showing totals

### ISSUE THREAD

**Issue by assadnazar** [EPPlusSoftware/EPPlus#490]
Hi everyone,
I am implementing [this example](https://github.com/EPPlusSoftware/EPPlus/wiki/LoadFromCollection-using-Attributes) but the totals are not showing up. 

Details are provided in this [stackoverflow question](https://stackoverflow.com/questions/69243763/epplus-attributes-totals-row)

Any help will be appreciated.

[Update]
I am able to get the totals with also adding **TableStyle = TableStyles.{any option other than none}** in **EpplusTable** attribute. This should an optional parameter.

**Comment by swmal** [comment]
Hi,
thanks for reporting, we'll have a look at this.
/Mats

**Comment by swmal** [comment]
This was a bug that occurred when TableStyle was None. It has been fixed in our develop branch and will be included in the next version that we will release in the coming days.

You can try it out in our [develop nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed) if you like.

**Comment by swmal** [comment]
Fixed in 5.7.5
