### ISSUE TITLE
Function ROMAN() works not always correctly

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#770]
I noticed, that the function ROMAN() sometimes delivers not correct results i.e. not equal to what excel does. I created an excel file with all possible function arguments and all possible convertable numbers and let a unit test compare excel calculation results with those from EPPlus. Here are my findings:

```
using var p = new ExcelPackage();
p.Workbook.Worksheets.Add("first");

var sheet = p.Workbook.Worksheets.First();

sheet.Cells["A1"].Formula = "=Roman(9.99)";
sheet.Cells["A2"].Formula = "=Roman(999;1)";
sheet.Cells["A3"].Formula = "=Roman(45;true)";
sheet.Cells["A4"].Formula = "=Roman(499;false)";

sheet.Calculate();

Assert.AreEqual("IX", sheet.Cells["A1"].Value.ToString());
Assert.AreEqual("LMVLIV", sheet.Cells["A2"].Value.ToString());
Assert.AreEqual("XLV", sheet.Cells["A3"].Value.ToString());
Assert.AreEqual("ID", sheet.Cells["A4"].Value.ToString());
```

I analyzed this findings today and will create a pull request with my fixes

But generally it would be a good idea to add such unit test. I will attach my excel file.

[Roman_allNumbers.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10314546/Roman_allNumbers.xlsx)

**Comment by swmal** [comment]
Hi,

I have added this fix to our codebase. I did it via a separate commit as I moved your unit test into our [MathFunctionsTest](https://github.com/EPPlusSoftware/EPPlus/blob/bug/roman_errors/src/EPPlusTest/FormulaParsing/Excel/Functions/MathFunctionsTests.cs#L456) instead of having it in the Issues test class.

Will be included in next revision.

/Mats

**Comment by ihorbach** [comment]
Hi Mats, 
perfect, thank you
