### ISSUE TITLE
epplus 6.2   InsertRow can't update formula

### ISSUE THREAD

**Issue by webcrack4** [EPPlusSoftware/EPPlus#837]
![image](https://user-images.githubusercontent.com/12699009/229797723-1035872d-cab4-40d9-b40c-ac8bd12fd83d.png)
The formula works on version epplus 4.5.3.3.

**Comment by JanKallman** [comment]
Please attach a reproducible sample.

**Comment by JanKallman** [comment]
We fixed a similar issue in 6.2.2, so I'll close this

**Comment by SeanFeldman** [comment]
The 6.2.2 version fixes formula adjustment but still has the same issue the produced spreadsheets had before. When the updated spreadsheet document is opened, Excel (version ???) shows a warning. 

![image](https://user-images.githubusercontent.com/1309622/234765547-364844c3-fa9d-4bf0-a5f4-3250d25df2bc.png)

When 'Yes' is selected (the only option to open the spreadsheet), the following repairs report is presented.

![image](https://user-images.githubusercontent.com/1309622/234765751-83fc06d4-e31b-40b4-a13f-bbc50c64eccd.png)

Repairs log file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <logFileName>error428760_04.xml</logFileName>
    <summary>Errors were detected in file '***redacted***\test.xlsx'</summary>
    <repairedParts>
        <repairedPart>Repaired Part: /xl/worksheets/sheet1.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet2.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet3.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet4.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet5.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet6.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet7.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet8.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet9.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
        <repairedPart>Repaired Part: /xl/worksheets/sheet10.xml part with XML error.  Load error. Line 1, column 0.</repairedPart>
    </repairedParts>
</recoveryLog>
```

I've compared the contents of the updated (original) `.xslx` and the one fixed by Excel and noticed an a `calcChain.xml` file that was added to the fixed `.xslx`.

![image](https://user-images.githubusercontent.com/1309622/234768781-f490cc56-6bab-4ce0-86af-88450ed5c6fd.png)

**Comment by JanKallman** [comment]
Can you provide some sample code and a workbook if needed to reproduce this issue?

**Comment by SeanFeldman** [comment]
@JanKallman, we'd have to switch to a private channel - the "template" spreadsheet is not something I'd be able to share publicly.
You can reach me at feldman.sean at gmail.

**Comment by JanKallman** [comment]
Do you have a commercial license? In that case, please use our support portal from your account at our web site.
